### PR TITLE
Qt6 migration

### PR DESCRIPTION
**Pull request by kaixoo**
- [ ] QMatrix has been removed from Qt6; replace it (with SkMatrix?).
- [ ] Update build instructions with qt6 packages

### CODE REVIEW

**Comment by kaixoo** [comment]
Hi! I am getting the following error:

```cmake
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find required Qt component "Qml".
```

How do I get this component from apt?

**Comment by rodlie** [comment]
We are not migrating to Qt6. Friction will use Qt 5.15 for the foreseeable future.

Even if we where to migrate to Qt6 you are doing it the wrong way. Why update the builds scripts? That's the last thing that needs changes.

How am I supposed to review this PR?

Feel free to discuss Qt6 in #9

**Comment by kaixoo** [comment]
> We are not migrating to Qt6. Friction will use Qt 5.15 for the foreseeable future.

Can't we migrate to Qt6 and maintain support for Qt 5.15?

**Comment by rodlie** [comment]
> Can't we migrate to Qt6 and maintain support for Qt 5.15?

If you want to help with Qt6 consider fixing deprecated things first, like:

* Replace `QRegExp` with `QRegularExpression`
  * https://github.com/search?q=repo%3Afriction2d%2Ffriction%20QRegExp&type=code

Review what is removed/deprecated in Qt 6.5, the majority of changes can probably still be done on Qt 5.15, if some code only works on Qt6 add ifdef.

Use #9 to track/plan/discuss the progress. Add what needs to be done in a list or something. Communicate (with me) before starting a PR related to Qt6.

**Pull request closed without merging**
