### PR TITLE
macOS - Fix duplicate command

### PR DESCRIPTION
**Pull request by pgilfernandez**
I tested it and now it works... it was my mixed branch which made strange things...
So, this helps fixing https://github.com/friction2d/friction/issues/324 issues

The rest looks like it works... any issue you found in the middle?

### CODE REVIEW

**Comment by rodlie** [comment]
This change will break 'duplicate' for objects, it needs fixes for focus to work properly.

I did some changes on my macbook last night, not done/committed yet, as I want to fix all the shortcuts (delete etc) in one go.

**Comment by pgilfernandez** [comment]
> This change will break 'duplicate' for objects, it needs fixes for focus to work properly.

Umm, yes, I test cmd+D and it doesn't duplicate objects only when you have a keyframe also selected, if they are just objects they are duplicated correctly.

> I did some changes on my macbook last night, not done/committed yet, as I want to fix all the shortcuts (delete etc) in one go.

Great, let me know when you have something finished and I will test it here as well.

Thanks

**Comment by rodlie** [comment]
> let me know when you have something finished

Will do, after work.

**Comment by rodlie** [comment]
This has been fixed in another commit, closing.

**Pull request closed without merging**
