### PR TITLE
New null object type

### PR DESCRIPTION
**Pull request by pgilfernandez**
Playing with null objects felt like adding a new one "crosshair":

Screenshot 2024-11-22 at 23 35 16

I hope you like it.

I tried opening a file with the new target on an "old Friction build" and it opened it. It didn't show up any icon as its index didn't exist on that version but it just left it as a "blank type". Manually you can then change it to any existing type and "problem solved"... I mean, it's compatible.

Cheers

### CODE REVIEW

**Comment by rodlie** [comment]
Works for me.

But, you have introduced something new that affects the project format and need to bump the version.

Commit 2 seems like something we don't want, we are only backwards compatible not forward.

**Comment by pgilfernandez** [comment]
> Works for me.

Great

> But, you have introduced something new that affects the project format and need to bump the version.

Ouch, it feels like bumping the version is bad, hehehe. Does it worth it?

> Commit 2 seems like something we don't want, we are only backwards compatible not forward.

Umm, I did this commit because I was breaking it as in "commit 1" I used "square, circle, crosshair, triangle" but the most compatible option when going in any direction would be to have "square, circle, triangle, crosshair", doesn't it?

**Comment by pgilfernandez** [comment]
Actually:

- **backward compatibility** (open an old file in a new Friction version): with "commit 2" I fix this as if we use "square, circle, triangle, crosshair" any old file would just use the first 3 indexes (square, circle, triangle) so when loading it up in a new Friction version they would always work and apply the right null object type.

- **forward compatibility** (open a new file in an old Friction version): here is where we could try loading up the new null object type (index 3, crosshair) and it doesn't exist in the old Friction version. Here I checked that Friction loads it as "none" and it doesn't draw any null object type, but it doesn't crash, the object is loaded and you can just go to type and change it to any of the 3 types that exist in that old Friction version (square, circle or triangle).

Is that right?

**Comment by pgilfernandez** [comment]
Do you want me to try bumping version? I prefer you do it as you better control it all but let me know.

**Comment by rodlie** [comment]
No need to do anything, I will merge this later today.

**Comment by rodlie** [comment]
This PR will need to wait, I discovered a bug in null object.

1. New project
2. Add null object
3. Select circle or triangle
4. Save and close project
5. Open project, notice that the object is a square

If you change the size and save it works. So, for some reason the type is only set if size is set to something not default on project load.

**Comment by pgilfernandez** [comment]
I'm late but I see you found a way to solve it. Great!!

**Pull request merged**
